# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: smart_environment.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'smart_environment.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17smart_environment.proto\x12\x11smart_environment\",\n\x16\x44\x65viceDiscoveryRequest\x12\x12\n\ngateway_id\x18\x01 \x01(\t\"z\n\x17\x44\x65viceDiscoveryResponse\x12\x11\n\tdevice_id\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65vice_type\x18\x02 \x01(\t\x12\x12\n\nip_address\x18\x03 \x01(\t\x12\x0c\n\x04port\x18\x04 \x01(\x05\x12\x15\n\rinitial_state\x18\x05 \x01(\t\"5\n\x11\x44\x65viceStateUpdate\x12\x11\n\tdevice_id\x18\x01 \x01(\t\x12\r\n\x05state\x18\x02 \x01(\t\"B\n\rDeviceCommand\x12\x11\n\tdevice_id\x18\x01 \x01(\t\x12\x0f\n\x07\x63ommand\x18\x02 \x01(\t\x12\r\n\x05value\x18\x03 \x01(\t\"X\n\rClientRequest\x12\x14\n\x0crequest_type\x18\x01 \x01(\t\x12\x11\n\tdevice_id\x18\x02 \x01(\t\x12\x0f\n\x07\x63ommand\x18\x03 \x01(\t\x12\r\n\x05value\x18\x04 \x01(\t\"a\n\x0e\x43lientResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\x12.\n\x07\x64\x65vices\x18\x03 \x03(\x0b\x32\x1d.smart_environment.DeviceInfo\"C\n\nDeviceInfo\x12\x11\n\tdevice_id\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65vice_type\x18\x02 \x01(\t\x12\r\n\x05state\x18\x03 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'smart_environment_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DEVICEDISCOVERYREQUEST']._serialized_start=46
  _globals['_DEVICEDISCOVERYREQUEST']._serialized_end=90
  _globals['_DEVICEDISCOVERYRESPONSE']._serialized_start=92
  _globals['_DEVICEDISCOVERYRESPONSE']._serialized_end=214
  _globals['_DEVICESTATEUPDATE']._serialized_start=216
  _globals['_DEVICESTATEUPDATE']._serialized_end=269
  _globals['_DEVICECOMMAND']._serialized_start=271
  _globals['_DEVICECOMMAND']._serialized_end=337
  _globals['_CLIENTREQUEST']._serialized_start=339
  _globals['_CLIENTREQUEST']._serialized_end=427
  _globals['_CLIENTRESPONSE']._serialized_start=429
  _globals['_CLIENTRESPONSE']._serialized_end=526
  _globals['_DEVICEINFO']._serialized_start=528
  _globals['_DEVICEINFO']._serialized_end=595
# @@protoc_insertion_point(module_scope)
